branch-defaults:
  main:
    environment: profile-matching-env
    group_suffix: null

global:
  application_name: profile-matching
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application

option_settings:
  aws:autoscaling:launchconfiguration:
    InstanceType: t2.medium
  aws:elasticbeanstalk:application:environment:
    NODE_ENV: production
    PYTHON_PATH: /opt/python/current/app
    MONGODB_URI: ${MONGODB_URI}
    SECRET_API_KEY: ${SECRET_API_KEY}
  aws:elasticbeanstalk:container:python:
    WSGIPath: application:application
  aws:elasticbeanstalk:container:nodejs:
    NodeVersion: 18
    ProxyServer: nginx
